/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER
 */
public class AdminPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminPage
     */
    public AdminPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        mngDrButton = new javax.swing.JButton();
        mngOfficeStuffButton = new javax.swing.JButton();
        mngUserButton = new javax.swing.JButton();
        adminPanelButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        mngDrButton.setText("DOCTOR");
        mngDrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngDrButtonActionPerformed(evt);
            }
        });
        jPanel2.add(mngDrButton);
        mngDrButton.setBounds(155, 156, 130, 40);

        mngOfficeStuffButton.setText("OFFICE STAFF");
        mngOfficeStuffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngOfficeStuffButtonActionPerformed(evt);
            }
        });
        jPanel2.add(mngOfficeStuffButton);
        mngOfficeStuffButton.setBounds(431, 156, 137, 40);

        mngUserButton.setText("USER");
        mngUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngUserButtonActionPerformed(evt);
            }
        });
        jPanel2.add(mngUserButton);
        mngUserButton.setBounds(155, 268, 130, 40);

        adminPanelButton.setText("ADMIN PANEL");
        jPanel2.add(adminPanelButton);
        adminPanelButton.setBounds(431, 268, 137, 40);

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home button.jpg"))); // NOI18N
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        jPanel2.add(homeButton);
        homeButton.setBounds(10, 10, 60, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/signup bg.jpg"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 760, 540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mngDrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngDrButtonActionPerformed
        // TODO add your handling code here:
        ManageDoctor mngdr= new ManageDoctor();
            mngdr.show();
            dispose();
    }//GEN-LAST:event_mngDrButtonActionPerformed

    private void mngOfficeStuffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngOfficeStuffButtonActionPerformed
        // TODO add your handling code here:
        ManageOfficeStuff m = new ManageOfficeStuff();
        m.show();
        dispose();
    }//GEN-LAST:event_mngOfficeStuffButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        HomePage hmpg= new HomePage();
        hmpg.show();
        dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    private void mngUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngUserButtonActionPerformed
        // TODO add your handling code here:
        UserList ul = new UserList();
        ul.show();
        dispose();
    }//GEN-LAST:event_mngUserButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminPanelButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton mngDrButton;
    private javax.swing.JButton mngOfficeStuffButton;
    private javax.swing.JButton mngUserButton;
    // End of variables declaration//GEN-END:variables
}
