/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER
 */
public class Facility extends javax.swing.JFrame {

   
    
    
    public Facility() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        bedCabinButton = new javax.swing.JButton();
        cathLabButton = new javax.swing.JButton();
        ecgButton = new javax.swing.JButton();
        pathologyButton = new javax.swing.JButton();
        cardicButton = new javax.swing.JButton();
        xrayButton = new javax.swing.JButton();
        ctScanButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home button.jpg"))); // NOI18N
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(homeButton);
        homeButton.setBounds(10, 10, 60, 60);

        bedCabinButton.setText("Bed/Cabin And Other");
        bedCabinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bedCabinButtonActionPerformed(evt);
            }
        });
        jPanel1.add(bedCabinButton);
        bedCabinButton.setBounds(160, 120, 300, 35);

        cathLabButton.setText("Cath Lab Procedure");
        cathLabButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cathLabButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cathLabButton);
        cathLabButton.setBounds(520, 120, 300, 35);

        ecgButton.setText("Echo, ETT, ECG And Others");
        ecgButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecgButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ecgButton);
        ecgButton.setBounds(160, 210, 300, 35);

        pathologyButton.setText("Pathology Investigation");
        pathologyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathologyButtonActionPerformed(evt);
            }
        });
        jPanel1.add(pathologyButton);
        pathologyButton.setBounds(520, 210, 300, 35);

        cardicButton.setText("Cardiac Operation");
        cardicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardicButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cardicButton);
        cardicButton.setBounds(160, 290, 300, 35);

        xrayButton.setText("X-Ray And Ultrasonogram");
        xrayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xrayButtonActionPerformed(evt);
            }
        });
        jPanel1.add(xrayButton);
        xrayButton.setBounds(520, 290, 300, 35);

        ctScanButton.setText("CT Scan & CT Angiogram Investigation");
        ctScanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctScanButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ctScanButton);
        ctScanButton.setBounds(320, 390, 350, 35);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/facility bg.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1050, 650);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1043, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        HomePage hmpg= new HomePage();
        hmpg.show();
        dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    private void bedCabinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bedCabinButtonActionPerformed
        // TODO add your handling code here:
        Tests.a=1;
        Tests ts= new Tests();
        
        ts.show();
        dispose();
    }//GEN-LAST:event_bedCabinButtonActionPerformed

    private void cathLabButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cathLabButtonActionPerformed
        // TODO add your handling code here:
        Tests.a=2;
        Tests ts= new Tests();
        
        ts.show();
        dispose();
    }//GEN-LAST:event_cathLabButtonActionPerformed

    private void ecgButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecgButtonActionPerformed
        // TODO add your handling code here:
        Tests.a=3;
        Tests ts= new Tests();
        ts.show();
        dispose();
    }//GEN-LAST:event_ecgButtonActionPerformed

    private void pathologyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathologyButtonActionPerformed
        // TODO add your handling code here:
        Tests.a=4;
        Tests ts= new Tests();
        
        ts.show();
        dispose();
    }//GEN-LAST:event_pathologyButtonActionPerformed

    private void cardicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardicButtonActionPerformed
        // TODO add your handling code here:
        Tests.a=5;
        Tests ts= new Tests();
        
        ts.show();
        dispose();
    }//GEN-LAST:event_cardicButtonActionPerformed

    private void xrayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xrayButtonActionPerformed
        // TODO add your handling code here:
        Tests.a=6;
        Tests ts= new Tests();
        
        ts.show();
        dispose();
    }//GEN-LAST:event_xrayButtonActionPerformed

    private void ctScanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctScanButtonActionPerformed
        // TODO add your handling code here:
        Tests.a=7;
        Tests ts= new Tests();
        
        ts.show();
        dispose();
    }//GEN-LAST:event_ctScanButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Facility.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Facility.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Facility.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Facility.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Facility().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bedCabinButton;
    private javax.swing.JButton cardicButton;
    private javax.swing.JButton cathLabButton;
    private javax.swing.JButton ctScanButton;
    private javax.swing.JButton ecgButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton pathologyButton;
    private javax.swing.JButton xrayButton;
    // End of variables declaration//GEN-END:variables
}
