
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER
 */
public class ManageOfficeStuff extends javax.swing.JFrame {

    /**
     * Creates new form ManageOfficeStuff
     */
    public ManageOfficeStuff() {
        initComponents();
        showData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        firstName = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        dob = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        post = new javax.swing.JComboBox<>();
        bloodGroup = new javax.swing.JComboBox<>();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        clratButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);
        jPanel1.add(firstName);
        firstName.setBounds(52, 85, 190, 40);
        jPanel1.add(lastName);
        lastName.setBounds(364, 85, 190, 40);
        jPanel1.add(dob);
        dob.setBounds(671, 85, 190, 40);
        jPanel1.add(phone);
        phone.setBounds(52, 188, 190, 40);

        post.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nurse", "Wardboy", "Cleaner", "Guard" }));
        jPanel1.add(post);
        post.setBounds(364, 188, 190, 40);

        bloodGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "B+", "AB+", "O+", "A-", "B-", "AB-", "O-" }));
        jPanel1.add(bloodGroup);
        bloodGroup.setBounds(671, 188, 190, 40);

        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        jPanel1.add(updateButton);
        updateButton.setBounds(304, 305, 100, 35);

        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(deleteButton);
        deleteButton.setBounds(454, 305, 100, 35);

        clratButton.setText("CLEAR");
        clratButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clratButtonActionPerformed(evt);
            }
        });
        jPanel1.add(clratButton);
        clratButton.setBounds(634, 305, 100, 35);

        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addButton);
        addButton.setBounds(783, 305, 100, 35);

        jLabel1.setText("FIRST NAME");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(52, 56, 91, 20);

        jLabel2.setText("LAST NAME");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(364, 56, 86, 20);

        jLabel3.setText("DATE OF BIRTH (dd/mm/yyyy)");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(671, 56, 230, 20);

        jLabel4.setText("PHONE");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(52, 159, 52, 20);

        jLabel5.setText("POST");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(364, 159, 40, 20);

        jLabel6.setText("BLOOD GROUP");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(671, 159, 110, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "DATE OF BIRTH", "PHONE", "BLOOD GROUP", "POST"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(70, 520, 860, 120);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/manage dr bg.jpg"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(-60, 0, 1060, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1001, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        if(firstName.getText().equals("")&& dob.getText()== null && lastName.getText().equals("") ){
           
            JOptionPane.showMessageDialog(null,"Enter all information");
        }
        else{
            
            try{
                Conn c =new Conn();
                String data[]= {firstName.getText()+" "+ lastName.getText(),dob.getText(),phone.getText(),bloodGroup.getSelectedItem().toString(),post.getSelectedItem().toString()};
                DefaultTableModel tb1 =(DefaultTableModel)jTable1.getModel();
                tb1.addRow(data);
                String query ="insert into staff values( "+null+",'"+data[0]+"','"+data[1]+"','"+data[2]+"','"+data[3]+"','"+data[4]+"')";
                c.s.executeUpdate(query);
                
                
            }
            catch (Exception e)
            {
                e.printStackTrace();
            }
            firstName.setText("");
            lastName.setText("");
            dob.setText("");
            phone.setText("");
            
            
           
            
            JOptionPane.showMessageDialog(null,"Adder successfully");
            
        }
    }//GEN-LAST:event_addButtonActionPerformed

    public void showData(){
        
        try{
            
            Connection c = DriverManager.getConnection("jdbc:mysql:///hms","root","aust2021");
            Statement s= c.createStatement();
        String sql = "select * from staff";
        ResultSet rs= s.executeQuery(sql);
        DefaultTableModel tb1 =(DefaultTableModel)jTable1.getModel();
        
        
        while(rs.next()){
            String data[]={rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)};
            tb1.addRow(data);
        }
       
        }catch(Exception e){
            e.printStackTrace();
        }
        
        
    }
    
    
    private void clratButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clratButtonActionPerformed
        // TODO add your handling code here:
            firstName.setText("");
            lastName.setText("");
            dob.setText("");
            phone.setText("");
    }//GEN-LAST:event_clratButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb1 =(DefaultTableModel)jTable1.getModel();
        if(jTable1.getSelectedRowCount()==1){
            String data[]= {firstName.getText()+" "+ lastName.getText(),dob.getText(),phone.getText(),post.getSelectedItem().toString(),bloodGroup.getSelectedItem().toString()};
            
           
            
            tb1.setValueAt(data[0],jTable1.getSelectedRow(), 0);
            tb1.setValueAt(data[1],jTable1.getSelectedRow(), 1);
            tb1.setValueAt(data[2],jTable1.getSelectedRow(), 2);
            tb1.setValueAt(data[3],jTable1.getSelectedRow(), 3);
            tb1.setValueAt(data[4],jTable1.getSelectedRow(), 4);
            tb1.setValueAt(data[5],jTable1.getSelectedRow(), 5);
            
            
            
        }
        else{
            JOptionPane.showMessageDialog(null,"Please select one row where you want to update");
        }
        
        
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb1 =(DefaultTableModel)jTable1.getModel();
        if(jTable1.getSelectedRowCount()==1){
            
            tb1.removeRow(jTable1.getSelectedRow());
        }else {
            if(jTable1.getSelectedRowCount()==0){
            JOptionPane.showMessageDialog(null,"please select a row","warning",2);
            }
            else{
            JOptionPane.showMessageDialog(null,"Please select one row");
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageOfficeStuff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageOfficeStuff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageOfficeStuff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageOfficeStuff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageOfficeStuff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JComboBox<String> bloodGroup;
    private javax.swing.JButton clratButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField dob;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextField phone;
    private javax.swing.JComboBox<String> post;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
