
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER
 */
public class SignUpPage extends javax.swing.JFrame {

    /**
     * Creates new form SignUpPage
     */
    public SignUpPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        phoneNumber = new javax.swing.JTextField();
        firstPass = new javax.swing.JTextField();
        cnfrmPass = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        voterId = new javax.swing.JTextField();
        dob = new javax.swing.JTextField();
        jLevel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        clearButton = new javax.swing.JButton();
        signUp = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        gander = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);
        jPanel1.add(txtFirstName);
        txtFirstName.setBounds(129, 98, 200, 50);

        txtLastName.setToolTipText("");
        jPanel1.add(txtLastName);
        txtLastName.setBounds(411, 98, 200, 50);
        jPanel1.add(txtEmail);
        txtEmail.setBounds(129, 186, 482, 50);
        jPanel1.add(phoneNumber);
        phoneNumber.setBounds(129, 275, 482, 50);
        jPanel1.add(firstPass);
        firstPass.setBounds(130, 660, 200, 50);
        jPanel1.add(cnfrmPass);
        cnfrmPass.setBounds(410, 660, 200, 50);

        jLabel1.setText("First Name *");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(129, 69, 90, 20);

        jLabel2.setText("Last Name *");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(411, 69, 88, 20);

        jLabel3.setText("Email");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(129, 157, 39, 20);

        jLabel4.setText("Phone Number*");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(129, 246, 115, 20);

        jLabel5.setText("Password");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(130, 630, 67, 20);

        jLabel6.setText("Confirm Password");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(410, 630, 129, 20);
        jPanel1.add(voterId);
        voterId.setBounds(129, 372, 482, 50);
        jPanel1.add(dob);
        dob.setBounds(129, 467, 230, 47);

        jLevel7.setText("Voter ID");
        jPanel1.add(jLevel7);
        jLevel7.setBounds(129, 343, 60, 20);

        jLabel8.setText("Date Of Birth * (DD/MM/YYYY)");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(129, 438, 230, 20);

        clearButton.setText("CLEAR");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        jPanel1.add(clearButton);
        clearButton.setBounds(410, 730, 81, 29);

        signUp.setText("SIGN UP");
        signUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpActionPerformed(evt);
            }
        });
        jPanel1.add(signUp);
        signUp.setBounds(510, 730, 95, 29);

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home button.jpg"))); // NOI18N
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(homeButton);
        homeButton.setBounds(10, 10, 60, 60);

        jComboBox1.setBackground(new java.awt.Color(153, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "B+", "AB+", "O+", "A-", "B-", "AB-", "O-" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(420, 470, 190, 40);

        gander.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE" }));
        jPanel1.add(gander);
        gander.setBounds(130, 570, 190, 40);

        jLabel10.setText("Gander");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(130, 540, 51, 20);

        jLabel9.setText("Blood Group");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(420, 440, 110, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/signup bg.jpg"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 0, 740, 800);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        txtFirstName.setText("");
        txtLastName.setText("");
        voterId.setText("");
        txtEmail.setText("");
        phoneNumber.setText("");
        dob.setText("");
        firstPass.setText("");
        cnfrmPass.setText("");
        
    }//GEN-LAST:event_clearButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        HomePage hmpg= new HomePage();
        hmpg.show();
        dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    private void signUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpActionPerformed
        
        if(firstPass.getText().equals(cnfrmPass.getText()))
        {
        try {
            // TODO add your handling code here:
            Conn c = new Conn();
            String data[]={txtFirstName.getText()+" "+txtLastName.getText(),txtEmail.getText(),phoneNumber.getText(),voterId.getText(),dob.getText(),jComboBox1.getSelectedItem().toString(),gander.getSelectedItem().toString(),firstPass.getText()};
            String sql ="insert into user values('"+data[0]+"','"+data[1]+"','"+data[2]+"','"+data[3]+"','"+data[4]+"','"+data[5]+"','"+data[6]+"','"+data[7]+"')";
            c.s.executeUpdate(sql);
            
            
            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        }
        else{
            JOptionPane.showMessageDialog(null,"Enter Correct Password","Warning", 2);
        }
    }//GEN-LAST:event_signUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField cnfrmPass;
    private javax.swing.JTextField dob;
    private javax.swing.JTextField firstPass;
    private javax.swing.JComboBox<String> gander;
    private javax.swing.JButton homeButton;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLevel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField phoneNumber;
    private javax.swing.JButton signUp;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField voterId;
    // End of variables declaration//GEN-END:variables
}
