
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER
 */
public class Tests extends javax.swing.JFrame {

    public static int a=0;
    public Tests() {
        initComponents();
        jPanel2.setVisible(false);
        
        if (a==1)
        {
            String sql = "select * from facility WHERE type LIKE '%Bed/Cabin And Other%'";
            showData(sql);
        }
        else if(a==2)
        {
            String sql = "select * from facility WHERE type LIKE 'Cath Lab Procedure%'";
            showData(sql);
        }
        else if(a==3)
        {
            String sql = "select * from facility WHERE type LIKE '%Echo, ETT, ECG And Others%'";
            showData(sql);
        }
        else if(a==4)
        {
            String sql = "select * from facility WHERE type LIKE '%Pathology Investigation%'";
            showData(sql);
        }
        else if(a==5)
        {
            String sql = "select * from facility WHERE type LIKE '%Cardiac Operation%'";
            showData(sql);
        }
        else if(a==6)
        {
            String sql = "select * from facility WHERE type LIKE '%X-Ray And Ultrasonogram%'";
            showData(sql);
        }
        else if(a==7)
        {
            String sql = "select * from facility WHERE type LIKE '%CT Scan & CT Angiogram Investigation%'";
            showData(sql);
        }
        
        
    }

    public void showData(String sql){
        
        try{
            
            Connection c = DriverManager.getConnection("jdbc:mysql:///hms","root","aust2021");
            Statement s= c.createStatement();
        
        ResultSet rs= s.executeQuery(sql);
        DefaultTableModel tb1 =(DefaultTableModel)jTable1.getModel();
        
        
        while(rs.next()){
            String data[]={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)};
            tb1.addRow(data);
        }
        
       
            
        
        
            
        }catch(Exception e){
            e.printStackTrace();
        }
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        homeButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        level1 = new javax.swing.JLabel();
        level2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SL NO", "NAME OF TEST", "TAKA", "Type"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(110, 460, 880, 310);

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home button.jpg"))); // NOI18N
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(homeButton);
        homeButton.setBounds(10, 10, 60, 60);

        jPanel2.setLayout(null);

        level1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        level1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        level1.setText("name");
        level1.setToolTipText("");
        jPanel2.add(level1);
        level1.setBounds(10, 200, 490, 40);

        level2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        level2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        level2.setText("taka");
        jPanel2.add(level2);
        level2.setBounds(100, 240, 300, 40);

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(470, 0, 41, 29);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/facility icon.jpg"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(180, 40, 150, 160);

        jLabel4.setText("jLabel4");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 10, 290, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dr_details_bg.jpg"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 510, 330);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(270, 60, 510, 330);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/test.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1094, 778);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1092, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        HomePage hmpg= new HomePage();
        hmpg.show();
        dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        jPanel2.setVisible(true);
        DefaultTableModel tb1 =(DefaultTableModel)jTable1.getModel();
        String name = tb1.getValueAt(jTable1.getSelectedRow(), 1).toString();
        String taka = tb1.getValueAt(jTable1.getSelectedRow(), 2).toString()+" /- TK";
        
        level1.setText(name);
        level2.setText(taka);
        jLabel4.setText("Catagory: "+tb1.getValueAt(jTable1.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jPanel2.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tests().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton homeButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel level1;
    private javax.swing.JLabel level2;
    // End of variables declaration//GEN-END:variables
}
